# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y


CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y

# For split keyboards:
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Це ім'я, яке ви будете бачити на комп'ютері і до якого будете підключатися
CONFIG_ZMK_KEYBOARD_NAME="Corne_Home"

# --- НАЛАШТУВАННЯ ДЛЯ ЕКРАНА PROSPECTOR ---
# 1. Вмикаємо трансляцію статусу в ефір
CONFIG_ZMK_STATUS_ADVERTISEMENT=y

# 2. Позивний маяка. Має бути СУВОРО "MyKeyboard", бо саме його чекає готовий екран
CONFIG_ZMK_STATUS_ADV_KEYBOARD_NAME="MyKeyboard"

# 3. Передача рівня батареї правої половинки на головну плату (щоб екран бачив обидві)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# 4. Оптимізація батареї (передавати дані рідше, коли клавіатура не використовується)
CONFIG_ZMK_STATUS_ADV_ACTIVITY_BASED=y

